### ISSUE TITLE
Failure to parse post when author email not provided

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/jekyll-theme-open-project#74]
This crashes:
```
---
layout: post
title: "Yaml2Text now supports YAML with Liquid"
date: 2020-09-20
categories: about
authors:
  -
    name: Jeffrey Lau
    social_links:
      - https://www.linkedin.com/in/jtklau/

excerpt: >-
    Importing YAML data into Metanorma using Liquid!
---
```

This works:
```
---
layout: post
title: "Yaml2Text now supports YAML with Liquid"
date: 2020-09-20
categories: about
authors:
  -
    name: Jeffrey Lau
    email: xxx@abc.com
    social_links:
      - https://www.linkedin.com/in/jtklau/

excerpt: >-
    Importing YAML data into Metanorma using Liquid!
---
```
